---
- name: use tripleo-modify image
  hosts: undercloud-0
  gather_facts: yes
  any_errors_fatal: true
  pre_tasks:
  tasks:
    - name: Run modify image
      block:
        - include_tasks: pre.yml
        - include_tasks: deploy.yml
      when: test.tripleo.modify.image|default(False)

- name: Run post noop validation
  import_playbook: post.yml
